language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r ./python/test_requirements.txt
# command to run tests
script: cd python && python -m unittest discover
